# 1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = 
https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: 
A) Rank 
B) Name 
C) Artist 
D) Upload date 
E) Views

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
from selenium.common.exceptions import NoSuchElementException,ElementNotInteractableException,TimeoutException,StaleElementReferenceException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains

In [10]:
#loading driver
driver=webdriver.Chrome()
#loading page
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
wait=WebDriverWait(driver,10)
#declaring lists
rank=[]
name=[]
artist=[]
updateDate=[]
views=[]
#closing popup
try:
    wait.until(EC.element_to_be_clickable((By.XPATH,'//div[@class="frb-step frb-step-1"]/button[1]'))).click()
except:
    pass
#getting rank 
ranktag=wait.until(EC.presence_of_all_elements_located((By.XPATH,'//div[@id="mw-content-text"]/div/table[2]/tbody/tr/td[1]')))
for i in ranktag:
    rank.append(i.text)
#getting video names
nametag=wait.until(EC.presence_of_all_elements_located((By.XPATH,'//div[@id="mw-content-text"]/div/table[2]/tbody/tr/td[2]')))
for i in nametag:
    name.append(i.text)
#getting artist names
artisttag=wait.until(EC.visibility_of_all_elements_located((By.XPATH,'//div[@id="mw-content-text"]/div/table[2]/tbody/tr/td[3]')))
for i in artisttag:
    artist.append(i.text)
#getting update date 
datetag=wait.until(EC.visibility_of_all_elements_located((By.XPATH,'//div[@id="mw-content-text"]/div/table[2]/tbody/tr/td[4]')))
for i in datetag:
    updateDate.append(i.text)
viewstag=wait.until(EC.presence_of_all_elements_located((By.XPATH,'//div[@id="mw-content-text"]/div/table[2]/tbody/tr/td[5]')))
for i in ranktag:
    views.append(i.text)
driver.quit()
print(len(rank),len(name),len(artist),len(updateDate),len(views))

30 30 30 30 30

In [12]:
#creating dataframe
df=pd.DataFrame({"Rank":rank,"Video Name":name,"Artist":artist,"Update Date":updateDate,"Views":views})
df

,Rank,Video Name,Artist,Update Date,Views
0,1.,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - Kids' Songs & Stories,13.29,1.
1,2.,"""Despacito""[9]",Luis Fonsi,8.25,2.
2,3.,"""Johny Johny Yes Papa""[16]",LooLoo Kids - Nursery Rhymes and Children's Songs,6.78,3.
3,4.,"""Bath Song""[17]",Cocomelon - Nursery Rhymes,6.38,4.
4,5.,"""Shape of You""[18]",Ed Sheeran,6.07,5.
5,6.,"""See You Again""[21]",Wiz Khalifa,6.01,6.
6,7.,"""Wheels on the Bus""[26]",Cocomelon - Nursery Rhymes,5.53,7.
7,8.,"""Phonics Song with Two Words""[27]",ChuChu TV Nursery Rhymes & Kids Songs,5.47,8.
8,9.,"""Uptown Funk""[28]",Mark Ronson,5.02,9.
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[29]",Miroshka TV,4.96,10.
10,11.,"""Gangnam Style""[30]",officialpsy,4.88,11.
11,12.,"""Masha and the Bear – Recipe for Disaster""[35]",Get Movies,4.56,12.
12,13.,"""Dame Tu Cosita""[36]",Ultra Records,4.43,13.
13,14.,"""Axel F""[37]",Crazy Frog,4.04,14.
14,15.,"""Sugar""[38]",Maroon 5,3.93,15.
15,16.,"""Counting Stars""[39]",OneRepublic,3.86,16.
16,17.,"""Roar""[40]",Katy Perry,3.86,17.
17,18.,"""Baa Baa Black Sheep""[41]",Cocomelon - Nursery Rhymes,3.76,18.
18,19.,"""Waka Waka (This Time for Africa)""[42]",Shakira,3.71,19.
19,20.,"""Sorry""[43]",Justin Bieber,3.70,20.
20,21.,"""Lakdi Ki Kathi""[44]",Jingle Toons,3.67,21.
21,22.,"""Thinking Out Loud""[45]",Ed Sheeran,3.65,22.
22,23.,"""Dark Horse""[46]",Katy Perry,3.58,23.
23,24.,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.54,24.
24,25.,"""Perfect""[48]",Ed Sheeran,3.53,25.
25,26.,"""Faded""[49]",Alan Walker,3.51,26.
26,27.,"""Let Her Go""[50]",Passenger,3.50,27.
27,28.,"""Girls Like You""[51]",Maroon 5,3.47,28.
28,29.,"""Lean On""[52]",Major Lazer Official,3.45,29.
29,30.,"""Bailando""[53]",Enrique Iglesias,3.45,30.

# 2. Scrape the details team India’s international fixtures from bcci.tv. 
Url = https://www.bcci.tv/.
You need to find following details: 
A) Match title (I.e. 1 ODI) 
B) Series 
C) Place 
D) Date 
E) Time 
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [94]:
#loading driver
driver=webdriver.Chrome()
#loading page
driver.get('https://www.bcci.tv/')
wait=WebDriverWait(driver,10)
#declaring lists
Match_title=[]
Series=[]
Place=[]
Date=[]
Time=[]
#navigating to international fixtures
try:
    wait.until(EC.element_to_be_clickable((By.XPATH,'//a[text()="INTERNATIONAL"]'))).click()
except Exception as e:
    print(e)
try:
    cookiebtn=driver.find_element(By.XPATH,'//button[@class="cookie__accept btn btn-primary"]')
    cookiebtn.click()
except:
    pass
while True:
    #loading match title
    try:
        titletag=wait.until(EC.presence_of_all_elements_located((By.XPATH,'//div[@class="match-place ng-scope"]/span[1]')))
        for i in titletag:
            Match_title.append(i.text)
    except TimeoutException as e:
        print(e)
        print("Exception occured at Title tag, may be element is not located or any other error")
    #loading Series name
    try:
        try:
            liveseriestag=driver.find_element(By.XPATH,'//div[@class="match-card-top"]/div/h5')
            Series.append(liveseriestag.text)
        except:
            pass
        seriestag=wait.until(EC.presence_of_all_elements_located((By.XPATH,'//div[@class="match-card-top"]/h5')))
        for i in seriestag:
            Series.append(i.text)
    except TimeoutException as e:
        print(e)
        print("Exception occured at series tag, may be element is not located or any other error")
    #loading place
    try:
        placetag=wait.until(EC.presence_of_all_elements_located((By.XPATH,'//div[@class="match-place ng-scope"]')))
        for i in placetag:
            loc=re.sub(r'\w{3}\s\w{3,4}\s-\s','',str(i.text))
            Place.append(loc)
    except TimeoutException as e:
        print(e)
        print("Exception occured at place and stedium tag, may be element is not located or any other error")
    #loading date
    try:
        datetag=wait.until(EC.presence_of_all_elements_located((By.XPATH,'//div[@class="match-info"]/div[1]')))
        for i in datetag:
            Date.append(i.text)
    except TimeoutException as e:
        print(e)
        print("Exception occured at Date tag, may be element is not located or any other error")
    #loading time
    try:
        timetag=wait.until(EC.presence_of_all_elements_located((By.XPATH,'//div[@class="match-time no-margin ng-binding"]')))
        for i in timetag:
            Time.append(i.text)
    except TimeoutException as e:
        print(e)
        print("Exception occured at Time tag, may be element is not located or any other error")
    try:
       
        btn=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div[2]/div/button')
        btn.click()
    except NoSuchElementException:
        break
driver.quit()
print(len(Match_title),len(Series),len(Place),len(Date),len(Time))
#creating dataframe
df=pd.DataFrame({"Title":Match_title,"Series Name":Series,"place":Place,"Date":Date,"Time":Time})
df

119 119 119 119 119

,Title,Series Name,place,Date,Time
0,4th ODI -,ASIA CUP 2023,"R Premadasa International Stadium, Colombo",12 SEP 2023\n3:00 PM IST,3:00 PM IST
1,5th ODI -,ASIA CUP 2023,"R Premadasa International Stadium, Colombo",15 SEP 2023,3:00 PM IST
2,1st T20I -,19TH ASIAN GAMES 2023,"Pingfeng Cricket Field, Hangzhou",21 SEP 2023,6:30 AM IST
3,1st ODI -,AUSTRALIA TOUR OF INDIA 2023-24,"Punjab Cricket Association IS Bindra Stadium, ...",22 SEP 2023,1:30 PM IST
4,2nd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,"Holkar Cricket Stadium, Indore",24 SEP 2023,1:30 PM IST
...,...,...,...,...,...
114,1st Test -,ENGLAND TOUR OF INDIA 2023-24,"Rajiv Gandhi International Stadium, Hyderabad",25 JAN 2024,9:30 AM IST
115,2nd Test -,ENGLAND TOUR OF INDIA 2023-24,Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadi...,2 FEB 2024,9:30 AM IST
116,3rd Test -,ENGLAND TOUR OF INDIA 2023-24,"Saurashtra Cricket Association Stadium, Rajkot",15 FEB 2024,9:30 AM IST
117,4th Test -,ENGLAND TOUR OF INDIA 2023-24,"JSCA International Stadium Complex, Ranchi",23 FEB 2024,9:30 AM IST
118,5th Test -,ENGLAND TOUR OF INDIA 2023-24,"Himachal Pradesh Cricket Association Stadium, ...",7 MAR 2024,9:30 AM IST

# 3. Scrape the details of State-wise GDP of India from statisticstime.com. 
Url = http://statisticstimes.com/
You have to find following details: A)
Rank 
B) State 
C) GSDP(18-19)- at current prices 
D) GSDP(19-20)- at current prices 
E) Share(18-19) 
F) GDP($ billion) 
Note: - From statisticstimes home page you have to reach to economy page through code

In [26]:
#loading driver
driver=webdriver.Chrome()
#getting page
driver.get("http://statisticstimes.com/")
#maximizing screen
driver.maximize_window()
#declaring list
rank=[]
state=[]
gsdp18_19=[]
gsdp19_20=[]
share18_19=[]
GDP=[]
#navigating through economy navbar to india 
try:
    nav=driver.find_element(By.XPATH,'//div[@class="navbar"]/div[2]/button')
    indnav=driver.find_element(By.XPATH,'//div[@class="navbar"]/div[2]/div/a[3]')
    hover=ActionChains(driver).move_to_element(nav).click(indnav)
    hover.perform()
except NoSuchElementException:
    print("unable to locate element")
except ElementNotInteractableException:
    print("unable to click on element may be out of boundex or may be clearly not visible in under 1080 page resolution")

#going to state wise gdp page
try:
    driver.implicitly_wait(2)
    page=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
    page.click()
except NoSuchElementException as e:
    print(e)
    
#loading rank details
try:
    rnk=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
    for i in rnk:
        rank.append(i.text)
except NoSuchElementException as e:
    print(e)

#loading state names
try:
    sttag=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
    for i in sttag:
        state.append(i.text)
except NoSuchElementException as e:
    print(e)

#loading GSDP 18-19
try:
    gsdptag=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gsdptag:
        gsdp18_19.append(i.text)
except NoSuchElementException as e:
    print(e)
    
#loading GSDP 19-20
try:
    gsd20ptag=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gsd20ptag:
        gsdp19_20.append(i.text)
except NoSuchElementException as e:
    print(e)
    
#scraping share 18-19
try:
    sharetag=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
    for i in sharetag:
        share18_19.append(i.text)
except NoSuchElementException as e:
    print(e)
    
#scraping GDP details
try:
    gdptag=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
    for i in gdptag:
        GDP.append(i.text)
except NoSuchElementException as e:
    print(e)
    
driver.quit()   
#creating datafarame
df=pd.DataFrame({"Rank":rank,"State":state,"GSDP 18-19)":gsdp18_19,"GSDP 19-20":gsdp19_20,"Share 18-19":share18_19,"GDP($ billion)":GDP})
df

,Rank,State,GSDP 18-19),GSDP 19-20,Share 18-19,GDP($ billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 4. Scrape the details of trending repositories on Github.com. 
Url = https://github.com/
You have to find the following details: 
A) Repository title 
B) Repository description 
C) Contributors count 
D) Language used

In [65]:
#loading driver
driver=webdriver.Chrome()
#getting page
driver.get("https://github.com/")
#maximizing screen
driver.maximize_window()
#declaring list
url=[]
title=[]
desc=[]
contri_count=[]
languge=[]
#navigating through opensource navbar to trending repositories 
try:
    nav=driver.find_element(By.XPATH,'//div[@class="header-menu-wrapper d-flex flex-column flex-self-end flex-lg-row flex-justify-between flex-auto p-3 p-lg-0 rounded rounded-lg-0 mt-3 mt-lg-0"]/nav/ul/li[3]/button')
    trend=driver.find_element(By.XPATH,'//div[@class="header-menu-wrapper d-flex flex-column flex-self-end flex-lg-row flex-justify-between flex-auto p-3 p-lg-0 rounded rounded-lg-0 mt-3 mt-lg-0"]/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
    hover=ActionChains(driver).move_to_element(nav).click(trend)
    hover.perform()
except NoSuchElementException:
    print("unable to locate element")
except ElementNotInteractableException:
    print("unable to click on element may be out of boundex or may be clearly not visible in under 1080 page resolution")
driver.implicitly_wait(2)
#scrapping urls
try:
    urltag=driver.find_elements(By.XPATH,'//article[@class="Box-row"]/h2/a')
    for i in urltag:
        url.append(i.get_attribute('href'))
except NoSuchElementException as e:
    print(e)
#loading titles
try:
    titletag=driver.find_elements(By.XPATH,'//article[@class="Box-row"]/h2/a')
    for i in titletag:
        title.append(i.text)
except NoSuchElementException as e:
    print(e)
    
for link in url:
#     driver=webdriver.Chrome()
    driver.get(link)
    driver.implicitly_wait(2)
    #loading repositories description
    try:
        desctag=driver.find_element(By.XPATH,'//div[@class="BorderGrid-cell"]/p')
        desc.append(desctag.text)
    except NoSuchElementException:
         desc.append('-')
            
    #loading Contributors count 
    try:
        counttag=driver.find_element(By.XPATH,'//a[@class="Link--primary no-underline Link d-flex flex-items-center"]/span')
        contri_count.append(counttag.text)
    except NoSuchElementException:
        contri_count.append('-')
    #loading  Language used
    try:
        temp=[]
        lngtag=driver.find_elements(By.XPATH,'//ul[@class="list-style-none"]/li/a/span[1]')
        for i in lngtag:
            temp.append(i.text)
        languge.append(temp)
    except NoSuchElementException:
        languge.append('-')
    
    
#creating datafarame
df=pd.DataFrame({"Repository title":title,"Repository description":desc,"Contributors count ":contri_count,"Language used":languge})
df

,Repository title,Repository description,Contributors count,Language used
0,godotengine / godot,Godot Engine – Multi-platform 2D and 3D game e...,"2,202","[C++, C#, C, GLSL, Java, Python]"
1,rocketseat-education / nlw-ai-mastery,-,-,"[TypeScript, JavaScript, CSS, HTML]"
2,tldraw / tldraw,a very good whiteboard,125,"[TypeScript, CSS, JavaScript]"
3,FL33TW00D / whisper-turbo,Whisper on the web - turbocharged by your GPU 🏎️,,"[, TypeScript, CSS, JavaScript]"
4,lllyasviel / Fooocus,Focus on prompting and generating,4,"[Python, Jupyter Notebook]"
5,dataelement / bisheng,Bisheng is an open LLM devops platform for nex...,,"[Python, TypeScript, CSS, JavaScript, Dockerfi..."
6,microsoft / azurechat,🤖 💼 Azure Chat Solution Accelerator powered by...,14,"[TypeScript, Bicep, JavaScript, CSS]"
7,turboderp / exllamav2,A fast inference library for running LLMs loca...,,"[@oobabooga\n/ text-generation-webui, Python, ..."
8,TryQuiet / quiet,"A private, p2p alternative to Slack and Discor...",,"[@TryQuiet\n/ quiet, C, TypeScript, C++, Pytho..."
9,tairov / llama2.mojo,Inference Llama 2 in one file of pure 🔥,,"[Python, Dockerfile]"
10,apna-college / Delta,-,,"[HTML, JavaScript, EJS, CSS]"
11,mylxsw / aidea,AIdea 是一款支持 GPT 以及国产大语言模型通义千问、文心一言等，支持 Stable ...,,"[Dart, JavaScript, C++, CMake, Ruby, Swift]"
12,OpenPipe / OpenPipe,Turn expensive prompts into cheap fine-tuned m...,,"[TypeScript, Python, JavaScript]"
13,OpenBMB / AgentVerse,🤖 AgentVerse 🪐 provides a flexible framework t...,,"[JavaScript, TypeScript, Python]"
14,guoyww / AnimateDiff,Official implementation of AnimateDiff.,,"[Python, Shell]"
15,DataTalksClub / machine-learning-zoomcamp,The code from the Machine Learning Bookcamp bo...,,[Jupyter Notebook]
16,krahets / hello-algo,"《Hello 算法》：动画图解、一键运行的数据结构与算法教程，支持 Java, C++, P...",99,"[Java, Swift, C++, Go, Python, JavaScript]"
17,ianpatt / sfse,Starfield Script Extender,2,"[C++, C, CMake]"
18,laravel / framework,The Laravel Framework.,"3,202",[PHP]
19,steven-tey / dub,An open-source link shortener with built-in an...,,"[TypeScript, MDX]"
20,Snoopy1866 / LiTiaotiao-Custom-Rules,李跳跳自定义规则,2,[Java]
21,d2l-ai / d2l-zh,《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被70多个国家的500多所大学用于教学。,249,"[Python, HTML, TeX, Shell]"
22,microsoft / Web-Dev-For-Beginners,"24 Lessons, 12 Weeks, Get Started as a Web Dev...",,"[JavaScript, HTML, CSS, Vue]"
23,facebook / react-native,A framework for building native applications u...,,"[Java, C++, JavaScript, Objective-C++, Objecti..."
24,jedisct1 / libsodium,"A modern, portable, easy to use crypto library.",126,"[C, M4, Shell, Assembly, Makefile, Smarty]"

# 5. Scrape the details of top 100 songs on billiboard.com. Url = 
https:/www.billboard.com/
You have to find the following details: 
A) Song name 
B) Artist name 
C) Last week rank 
D) Peak rank 
E) Weeks on board 
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [79]:
#loading driver
driver=webdriver.Chrome()
#getting page
driver.get("https://www.billboard.com/")
#maximizing screen
driver.maximize_window()
#declaring list
song_name=[]
artist_name=[]
lW_rank=[]
p_rank=[]
wo_board=[]
#navigating on music page
try:
    menu_nav=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
    menu_nav.click()
    driver.execute_script("window.scrollTo(0,200)")
    chart=driver.find_element(By.XPATH,'//a[@class="c-link  lrv-a-unstyle-link lrv-u-background-color-brand-secondary-dark lrv-u-color-grey-lightest lrv-u-color-grey-lightest:hover lrv-u-width-100p lrv-u-text-align-center lrv-a-hover-effect lrv-u-background-color-grey-dark:hover a-font-accent-fancy lrv-u-font-size-20 u-padding-tb-15 u-letter-spacing-0112 lrv-a-icon-after a-icon-magazine lrv-u-justify-content-center lrv-u-align-items-center lrv-a-unstyle-link u-width-100p@tablet u-width-235@mobile-max lrv-u-margin-t-050@mobile-max u-background-color-white@mobile-max u-color-black@mobile-max lrv-u-border-a-1@mobile-max lrv-u-border-color-brand-accent-red u-line-height-1"]')
    chart.click()
except NoSuchElementException:
    print("unable to locate element")
except ElementNotInteractableException:
    print("unable to click on element may be out of boundex or may be clearly not visible in under 1080 page resolution")
try:
    popup=driver.find_element(By.XPATH,'//span[@class="floating-preroll-ad-close"]')
    popup.click()
    driver.execute_script("window.scrollTo(0,500)")
except:
    pass
driver.implicitly_wait(5)
#loading song names
try:
    song=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul[1]/li[1]/h3')
    for i in song:
        song_name.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading artist names
try:
    artist=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul[1]/li[1]/span')
    for i in artist:
        artist_name.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading last week rank
try:
    lwrank=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul[1]/li[4]/span')
    for i in lwrank:
        lW_rank.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading peak rank
try:
    prank=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul[1]/li[5]/span')
    for i in prank:
        p_rank.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading weeks on board
try:
    wotag=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul[1]/li[6]/span')
    for i in wotag:
        wo_board.append(i.text)
except NoSuchElementException as e:
    print(e)
    

    



    
driver.quit()   
#creating datafarame
df=pd.DataFrame({"Song name ":song_name,"Artist name ":artist_name,"Last week rank  ":lW_rank,"Peak rank ":p_rank,"Weeks on board ":wo_board})
df

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,Paint The Town Red,Doja Cat,3,1,5
1,I Remember Everything,Zach Bryan Featuring Kacey Musgraves,1,1,2
2,Fast Car,Luke Combs,2,2,24
3,Cruel Summer,Taylor Swift,5,3,18
4,Last Night,Morgan Wallen,4,1,32
...,...,...,...,...,...
95,Stand By Me,Lil Durk Featuring Morgan Wallen,93,22,15
96,Call Your Friends,Rod Wave,85,26,3
97,Your Heart Or Mine,Jon Pardi,72,47,17
98,Primera Cita,Carin Leon,97,97,2
99,S91,Karol G,86,45,6

# 6. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare 
You have to find the following details:
A) Book name 
B) Author name 
C) Volumes sold 
D) Publisher 
E) Genre

In [8]:
#loading driver
driver=webdriver.Chrome()
#getting page
driver.get(" https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
#maximizing screen
driver.maximize_window()
#declaring list
title=[]
authore=[]
publisher=[]
sales=[]
genere=[]
#loading book names
try:
    titletag=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in titletag:
        title.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading authore name
try:
    authoretag=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for i in authoretag:
        authore.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading publisher name
try:
    publishertag=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for i in publishertag:
        publisher.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading sales
try:
    salestag=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for i in salestag:
        sales.append(i.text)
except NoSuchElementException as e:
    print(e)

#loading genere type
try:
    generetag=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for i in generetag:
        genere.append(i.text)
except NoSuchElementException as e:
    print(e)
#closing driver       
driver.quit()   
#creating datafarame
df=pd.DataFrame({"Book name":title," Author name ":authore,"Volumes sold ":sales,"Publisher ":publisher,"Genre ":genere})
df

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 7. Scrape the details most watched tv series of all time from imdb.com. 
Url = https://www.imdb.com/list/ls095964455/ You 
have to find the following details: 
A) Name 
B) Year span 
C) Genre 
D) Run time 
E) Ratings 
F) Votes

In [9]:
#loading driver
driver=webdriver.Chrome()
#getting page
driver.get("https://www.imdb.com/list/ls095964455/")
#maximizing screen
driver.maximize_window()
#declaring list
name=[]
y_span=[]
genere=[]
run_t=[]
rating=[]
votes=[]

#loading book names
try:
    nametag=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
    for i in nametag:
        name.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading authore name
try:
    yspan=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]')
    for i in yspan:
        y_span.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading publisher name
try:
    runtime=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p/span[3]')
    for i in runtime:
        run_t.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading sales
try:
    rattag=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div/span[2]')
    for i in rattag:
        rating.append(i.text)
except NoSuchElementException as e:
    print(e)

#loading genere type
try:
    generetag=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p/span[5]')
    for i in generetag:
        genere.append(i.text)
except NoSuchElementException as e:
    print(e)
#loading genere type
try:
    vottag=driver.find_elements(By.NAME,'nv')
    for i in vottag:
        votes.append(i.text)
except NoSuchElementException as e:
    print(e)
    
#closing driver       
driver.quit()   
#creating datafarame
df=pd.DataFrame({"Name":name," Year Span ":y_span,"Genere ":genere,"Run Time ":run_t,"Rating ":rating,"Votes":votes})
df

,Name,Year Span,Genere,Run Time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,203,229"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,275,003"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,045,436"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"307,251"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"266,353"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.5,"52,705"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"64,755"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"210,967"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"43,885"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"265,756"

# 8. Details of Datasets from UCI machine learning repositories. 
Url = https://archive.ics.uci.edu/
You have to find the following details: 
A) Dataset name 
B) Data type 
C) Task 
D) Attribute type 
E) No of instances 
F) No of attribute G) Year 
Note: - from the home page you have to go to the Show All Dataset page through code.

In [6]:
#loading driver
driver=webdriver.Chrome()
#getting page
driver.get("https://archive.ics.uci.edu/")
#maximizing screen
driver.maximize_window()
#declaring list
link=[]
name=[]
dtype=[]
task=[]
atrtype=[]
n_instances=[]
n_atr=[]
year_note=[]

#loading book names
try:
    view=driver.find_element(By.XPATH,"//a[@class='btn-primary btn']")
    view.click()
except NoSuchElementException as e:
    print(e)
    
while True:
    #extracting links
    try:
        linktag=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
        for i in linktag:
            link.append(i.get_attribute('href'))
    except Exception as e:
        print('1',e)
    try:
        driver.find_element(By.TAG_NAME,'body').send_keys(Keys.END)
        nextbtn=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.XPATH,'//div[@class="btn-group"]/button[2]'))).click()
    except Exception as e:
        break
#visiting each link
for l in link:
    driver.get(l)
    #scraping dataset name
    try:
        nametag=driver.find_element(By.XPATH,'//h1[@class="text-3xl font-semibold text-primary-content"]')
        name.append(nametag.text)
    except NoSuchElementException:
        name.append('-')
    #scraping datatype
    try:
        datatype=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[4]/p')
        dtype.append(datatype.text)
    except NoSuchElementException:
        dtype.append('-')
    #scraping task
    try:
        tasktag=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[3]/p')
        task.append(tasktag.text)
    except NoSuchElementException:
        task.append('-')
    #scraping atribute type
    try:
        atrtag=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[1]/p')
        atrtype.append(atrtag.text)
    except NoSuchElementException:
        atrtype.append('-')
    #scraping no of instances
    try:
        ninstancestag=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[5]/p')
        n_instances.append(ninstancestag.text)
    except NoSuchElementException:
        n_instances.append('-')
    #scraping no of atributes
    try:
        n_atrtag=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[6]/p')
        n_atr.append(n_atrtag.text)
    except NoSuchElementException:
        n_atr.append('-')
     #scraping the year note
    try:
        year_notetag=driver.find_element(By.XPATH,'//h2[@class="text-sm text-primary-content"]')
        year_note.append(year_notetag.text)
    except NoSuchElementException:
        year_note.append('-')
        
#closing driver       
driver.quit()   
#creating datafarame
df=pd.DataFrame({" Dataset name":name," Data type ":dtype,"Task  ":task,"Attribute type ":atrtype,"No of instances  ":n_instances," No of attribute":n_atr,"Year Note":year_note})
df

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year Note
0,Iris,Real,Classification,Tabular,150,4,Donated on 6/30/1988
1,Heart Disease,"Categorical, Integer, Real",Classification,Multivariate,303,13,Donated on 6/30/1988
2,Adult,"Categorical, Integer",Classification,Multivariate,48842,14,Donated on 4/30/1996
3,Dry Bean Dataset,"Integer, Real",Classification,Multivariate,13611,16,Donated on 9/13/2020
4,Diabetes,"Categorical, Integer",-,"Multivariate, Time-Series",-,20,-
...,...,...,...,...,...,...,...
645,Wine,"Integer, Real",Classification,Tabular,178,13,Donated on 6/30/1991
646,Breast Cancer Wisconsin (Diagnostic),Real,Classification,Multivariate,569,30,Donated on 10/31/1995
647,Car Evaluation,Categorical,Classification,Multivariate,1728,6,Donated on 5/31/1997
648,Rice (Cammeo and Osmancik),Real,Classification,Multivariate,3810,7,Donated on 10/5/2019
649,Mushroom,Categorical,Classification,Multivariate,8124,22,Donated on 4/26/1987